--TBLOGRENCILER tablosunda yer alan kulüplerin deðerlerini numara ile belirleme (Birleþtirme iþlemi yapmak için TBLKULUPLER isminde yeni bir tablo oluþturduk.)
--UPDATE TBLOGRENCILER SET OGRKULUP=1 WHERE OGRKULUP='Biliþim'
--UPDATE TBLOGRENCILER SET OGRKULUP=2 WHERE OGRKULUP='Kitaplýk'
--UPDATE TBLOGRENCILER SET OGRKULUP=3 WHERE OGRKULUP='Satranç'
--UPDATE TBLOGRENCILER SET OGRKULUP=4 WHERE OGRKULUP='Gezi'
--UPDATE TBLOGRENCILER SET OGRKULUP=5 WHERE OGRKULUP='Temizlik'

--TBLOGRENCILER tablosuna yeni öðrenci ekleme
--INSERT INTO TBLOGRENCILER (OGRAD,OGRKULUP,OGRSEHIR) VALUES ('Berna',4,'Ankara')

--Birleþtirme Ýþlemleri (JOIN)
--TBLNOTLAR VE TBLDERSLER tablolarýnda yer alan NOTID deðerine göre DERSAD sütununda yer alan derslerin adýný getiren sorgu
--SELECT NOTID,DERSAD FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID

--TBLNOTLAR VE TBLDERSLER tablolarýnda yer alan NOTID deðerine göre DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM sütunundaki seçilen deðerleri getiren sorgu
--SELECT NOTID,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID

--TBLNOTLAR VE TBLDERSLER tablolarýnda yer alan NOTID deðerine göre DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM sütunundaki seçilen deðerleri getiren ve buna ek olarak 
-- TBLOGRENCILER tablosunda yer alan OGRAD deðerini getiren sorgu
--SELECT NOTID,OGRAD,DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER
--ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--TBLNOTLAR VE TBLDERSLER tablolarýnda yer alan NOTID deðerine göre DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM sütunundaki seçilen deðerleri getiren ve buna ek olarak 
-- TBLOGRENCILER tablosunda yer alan OGRAD ve OGRSOYAD deðerini getiren sorgu (OGRAD ve OGRSOYAD tek bir sütunda yazýlacak)
--SELECT NOTID,OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER
--ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID

--Ödev: DURUM kýsmýnda 1 ya da 0 yazmasýn, GEÇTÝ ya da KALDI yazsýn.
--SELECT NOTID,OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,SINAV2,SINAV3,ORTALAMA,CASE WHEN DURUM=1 THEN 'GEÇTÝ' ELSE 'KALDI' END AS 'SONUÇ' FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLNOTLAR.DERS = TBLDERSLER.DERSID
--INNER JOIN TBLOGRENCILER
--ON TBLNOTLAR.OGRENCI = TBLOGRENCILER.OGRID