--TBLNOTLAR tablosunu güncelleme
--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1
--UPDATE TBLNOTLAR SET DURUM=1 WHERE ORTALAMA >= 50
--UPDATE TBLNOTLAR SET DURUM=0 WHERE ORTALAMA < 50

--Alt Sorgu
--TBLDERSLER tablosunda yer alan ismi 'Matematik' olan derse ait not bilgilerini görüntüleme
--SELECT * FROM TBLNOTLAR WHERE DERS=(SELECT DERSID FROM TBLDERSLER WHERE DERSAD='Matematik')

--Ödev: TBLNOTLAR tablosundaki 'Algoritma' dersine ait en yüksek SINAV1'i getiren sorgu
--SELECT MAX(SINAV1) FROM TBLNOTLAR WHERE DERS=(SELECT DERSID FROM TBLDERSLER WHERE DERSAD='Algoritma')