--PARAMETRELÝ PROSEDÜR KULLANIMI

--Prosedür oluþturmak için
--CREATE PROCEDURE URUNGETIR
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--EXECUTE URUNGETIR

--Prosedürü güncellemek için
--ALTER PROCEDURE URUNGETIR
--AS
--SELECT URUNSTOK,URUNMARKA FROM TBLURUNLER
--EXECUTE URUNGETIR

--Paremetre eklemek için
--ALTER PROCEDURE URUNGETIR
--@Deger varchar(50)='BUZDOLABI'
--AS
--SELECT URUNAD,URUNSTOK,URUNMARKA FROM TBLURUNLER
--WHERE URUNAD=@Deger
--EXECUTE URUNGETIR

--EXECUTE URUNGETIR @Deger='ÇAMAÞIR MAKÝNESÝ'
--EXECUTE URUNGETIR @Deger='LAPTOP'

--Ödev: Stok sayýsý 10'dan büyük olan ürünleri getiren prosedürü yazýn.Stok sayýsýný dýþarýdan alýn.
--CREATE PROCEDURE STOKSAYISI10DANBUYUKOLANLAR
--AS
--SELECT URUNID,URUNAD,URUNMARKA,URUNSTOK FROM TBLURUNLER

--ALTER PROCEDURE STOKSAYISI10DANBUYUKOLANLAR
--@Stokdeger smallint
--AS
--SELECT URUNID,URUNAD,URUNMARKA,URUNSTOK FROM TBLURUNLER
--WHERE URUNSTOK>@Stokdeger

--EXECUTE STOKSAYISI10DANBUYUKOLANLAR @Stokdeger=10

