--PROSEDÜR OLUÞTURMA
--CREATE PROCEDURE HAREKETLER
--AS
--SELECT HAREKETID,URUNAD,MUSTERIAD + ' ' + MUSTERISOYAD AS 'AD SOYAD', PERSONELADSOYAD,ADET,TUTAR,TARIH FROM TBLHAREKET
--INNER JOIN TBLURUNLER ON TBLURUNLER.URUNID = TBLHAREKET.URUN
--INNER JOIN TBLMUSTERI ON TBLMUSTERI.MUSTERIID = TBLHAREKET.MUSTERI
--INNER JOIN TBLPERSONEL ON TBLPERSONEL.PERSONELID = TBLHAREKET.PERSONEL

--Prosedürümüzü çalýþtýrma
--EXECUTE HAREKETLER