--PROSEDÜR SÝLME VE GÜNCELLEME (DROP & ALTER)
--CREATE PROCEDURE DENEME
--AS
--SELECT * FROM TBLURUNLER WHERE URUNSTOK>10
--EXEC DENEME

--Prosedür Silme Ýþlemi
--DROP PROCEDURE DENEME

--Prosedür Güncelleme Ýþlemi
--ALTER PROCEDURE [dbo].[HAREKETLER]
--AS
--SELECT HAREKETID,URUNAD,LEFT(MUSTERIAD,1) + '.' + MUSTERISOYAD AS 'AD SOYAD', PERSONELADSOYAD,ADET,TUTAR,TARIH FROM TBLHAREKET
--INNER JOIN TBLURUNLER ON TBLURUNLER.URUNID = TBLHAREKET.URUN
--INNER JOIN TBLMUSTERI ON TBLMUSTERI.MUSTERIID = TBLHAREKET.MUSTERI
--INNER JOIN TBLPERSONEL ON TBLPERSONEL.PERSONELID = TBLHAREKET.PERSONEL
--EXEC HAREKETLER