--Tablo Sonuçlu Fonksiyonlar

--CREATE FUNCTION URUNBILGI(@URID INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE URUNID=@URID
--SELECT * FROM DBO.URUNBILGI(4)

--Ödev: Stok sayýsýný girdiðiniz zaman bu stok sayýsýnýn altýnda olan ürünleri getiren fonksiyonu yazýnýz.
--CREATE FUNCTION STOKSAYISIALTINDA(@STOKSAYISI INT)
--RETURNS TABLE
--AS
--RETURN SELECT * FROM TBLURUN WHERE STOK<@STOKSAYISI
--SELECT * FROM DBO.STOKSAYISIALTINDA(50)