--KDV Fonksiyonu

--CREATE FUNCTION KDV(@FIYAT DECIMAL(18, 2))
--RETURNS DECIMAL(18, 2)
--AS
--BEGIN
--RETURN @FIYAT*1.18
--END

--SELECT AD,SATISFIYAT,DBO.KDV(SATISFIYAT) AS 'KDVLÝ HALÝ' FROM TBLURUN