--STRING Türde Fonksiyon Oluþturma
--CREATE FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END
--Burada RETURNS VARCHAR ifadesinden sonra VARCHAR(20) yazýlmamýþtýr, bunun için tekrardan düzenleme yapýyoruz.

--ALTER FUNCTION KUCUKHARF(@ISIM VARCHAR(20))
--RETURNS VARCHAR(20)
--AS
--BEGIN
--RETURN LOWER(@ISIM)
--END

--SELECT DBO.KUCUKHARF(AD),STOK FROM TBLURUN