--TRANSACTION COMMIT

BEGIN TRANSACTION
INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN1',25)
INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN2',40)
INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN3',10)
INSERT INTO TBLURUN (AD,STOK) VALUES ('ÜRÜN4','B')
SELECT * FROM TBLURUN
COMMIT