--ALT SORGU ÖRNEKLERÝ

--Her bir üründen kaç adet satýldýðýný bulan sorgu
SELECT URUNAD,COUNT(*) AS 'SATILAN ADET SAYISI' FROM TBLHAREKET 
INNER JOIN TBLURUNLER ON TBLURUNLER.URUNID = TBLHAREKET.URUN
GROUP BY URUNAD ORDER BY COUNT(*) ASC

--Ürünler içerisinde sadece BÝLGÝSAYAR kategorisine ait satýlmýþ olan ürünleri listeleyen sorgu
SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE KATEGORI=1)

--Ödev: Ürünler tablosu içerisinde bulunan Kategori deðeri 1 deðil de BÝLGÝSAYAR olarak getiren sorgu
SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE KATEGORI IN(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BÝLGÝSAYAR'))