--Hareket tablosunun içerisinde yer alan þehri ADANA olan müþterileri listeleyen sorgu
--SELECT * FROM TBLHAREKET WHERE MUSTERI IN(SELECT MUSTERIID FROM TBLMUSTERI WHERE MUSTERISEHIR = 'ADANA')

--BEYAZ EÞYA kategorisindeki yapýlan harcamalarý getiren sorgu
SELECT * FROM TBLHAREKET WHERE URUN IN(SELECT URUNID FROM TBLURUNLER WHERE KATEGORI=(SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD='BEYAZ EÞYA'))