--TRIGGER (TETÝKLEYÝCÝLER)

--CREATE TABLE TBLSAYAC
--(
--ISLEM int
--)

--INSERT INTO TBLSAYAC VALUES (0)

--UPDATE TBLSAYAC SET ISLEM = (SELECT COUNT(*) FROM TBLHAREKET)

--Trigger Oluþturma
--CREATE TRIGGER ISLEMARTIS
--ON TBLHAREKET
--AFTER INSERT
--AS
--UPDATE TBLSAYAC SET ISLEM=ISLEM+1

--TBLTOPLAMKATEGORI TABLOSU OLUÞTURMA
--CREATE TABLE TBLTOPLAMKATEGORI
--(
--ADET tinyint
--)
--UPDATE TBLTOPLAMKATEGORI SET ADET = (SELECT COUNT(*) FROM TBLKATEGORI)

--Yeni bir kategori eklediðimizde TBLTOPLAMKATEGORI tablosunda birer arttýran tetikleyici sorgusu
--CREATE TRIGGER KATEGORIARTIS
--ON TBLKATEGORI
--AFTER INSERT
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET+=1

--Bir kategori sildiðimizde TBLTOPLAMKATEGORI tablosunda birer azaltan tetikleyici sorgusu
--CREATE TRIGGER KATEGORIAZALIS
--ON TBLKATEGORI
--AFTER DELETE
--AS
--UPDATE TBLTOPLAMKATEGORI SET ADET-=1