--UPDATE ile ilgili örnekler
--UPDATE TBLURUNLER SET URUNAD='SU ISITICI' WHERE URUNAD='KETTLE'

--TBLKATEGORI ile TBLURUNLER tablolarý arasýnda kategorinin adlarýný ve sayýsýný görüntüleyen ve sayýlarý küçükten büyüðe doðru sýralayan sorgu
--SELECT KATEGORIAD,COUNT(*) AS 'TOPLAM ÜRÜN' FROM TBLURUNLER 
--INNER JOIN TBLKATEGORI ON TBLKATEGORI.KATEGORIID=TBLURUNLER.KATEGORI 
--GROUP BY KATEGORIAD
--ORDER BY COUNT(*)

--Kategorinin ismi BÝLGÝSAYAR olan ürünlerin satýþ fiyatýný 500 lira zam yapan sorgu
--UPDATE TBLURUNLER SET URUNSATISFIYAT += 500 WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'BÝLGÝSAYAR')
--SELECT * FROM TBLURUNLER

--ÖDEV: TV kategorisindeki ürünlerin satýþ fiyatýný yüzde 10 indirim yapan sorguyu yazýn.
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT - URUNSATISFIYAT * 0.10 WHERE KATEGORI = (SELECT KATEGORIID FROM TBLKATEGORI WHERE KATEGORIAD = 'TV')

--TBLURUNLER tablosunda kaç farklý ürün olan ve stok sayýsýný toplayan sorgu
--SELECT COUNT(*) AS 'KAÇ FARKLI ÜRÜN', SUM(URUNSTOK) AS 'STOK SAYISI' FROM TBLURUNLER

--Buzdolabý kategorisinde yer alan ürünlerin tamamý satýlýrsa kaç para kazandýðýmýzý bulan sorgu
--SELECT URUNID,URUNAD,URUNMARKA,KATEGORIAD,URUNSATISFIYAT,URUNALISFIYAT,URUNSTOK,
--(URUNSATISFIYAT - URUNALISFIYAT) AS 'KAR', (URUNSATISFIYAT - URUNALISFIYAT) * URUNSTOK AS 'TOPLAM KAR'
--FROM TBLURUNLER INNER JOIN TBLKATEGORI ON TBLURUNLER.KATEGORI = TBLKATEGORI.KATEGORIID

--ÖDEV: Toplam kar 1000 liranýn altýnda kalan ürünlerin satýþ fiyatýna yüzde 20 zam yapan sorguyu yazýn.
--UPDATE TBLURUNLER SET URUNSATISFIYAT = URUNSATISFIYAT + URUNSATISFIYAT * 0.20
--WHERE (URUNSATISFIYAT - URUNALISFIYAT) * URUNSTOK < 1000