--DML Komutlarý

--Veri Ekleme Ýþlemleri
--TBLKATEGORI için veri ekleme
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BÝLGÝSAYAR')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('BEYAZ EÞYA')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('KÜÇÜK EV ALETÝ')
INSERT INTO TBLKATEGORI (KATEGORIAD) VALUES ('TV')

--TBLURUNLER için veri ekleme
INSERT INTO TBLURUNLER (URUNAD,URUNMARKA,KATEGORI,URUNALISFIYAT,URUNSATISFIYAT,URUNSTOK)
VALUES ('BUZDOLABI','SIEMENS',2,4356,4588,10)

--TBLURUNLER verileri görüntüleme
SELECT * FROM TBLURUNLER