--MATEMATÝKSEL FONKSÝYONLAR

--ABS
--SELECT ABS(-85) AS 'MUTLAK'
--SELECT POWER(2,4) AS 'ÜS ALMA'

--TBLNOTLAR tablosunda yer alan SINAV1 notlarýnýn karelerini alan sorgu
--SELECT POWER(SINAV1,2) FROM TBLNOTLAR

--SELECT SQRT(786) AS 'KAREKÖK'

--SELECT FLOOR(4.86) AS 'TABAN', CEILING(4.86) AS 'TAVAN'

