--1 NUMARALI ÖÐRENCÝ = AYÞE ÇINAR

--TBLNOTLAR tablosunda yer alan 1 numaralý öðrencinin SINAV1'den aldýðý notlarýn toplamýný gösteren sorgu
--SELECT SUM(SINAV1) FROM TBLNOTLAR WHERE OGRENCI=1

--TBLNOTLAR tablosunda yer alan 1 numaralý öðrencinin SINAV1 ve DERS deðerlerini gösteren sorgu
--SELECT SINAV1,DERS FROM TBLNOTLAR WHERE OGRENCI=1

--TBLNOTLAR tablosunda yer alan 1 numaralý öðrencinin SINAV1 ve DERS adýný gösteren sorgu
--SELECT DERSAD,SINAV1 FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
--WHERE OGRENCI=1

--TBLNOTLAR tablosunda yer alan 1 numaralý öðrencinin SINAV1,SINAV2,SINAV3 ve DERS adýný bu kez alt sorgu halinde gösteren sorgu
--SELECT DERSAD,SINAV1,SINAV2,SINAV3 FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR')

--TBLNOTLAR tablosunda yer alan 1 numaralý öðrencinin SINAV1 deðerini toplayan ve ortalamasýný bulan sorgu
--SELECT SUM(SINAV1),AVG(SINAV1) FROM TBLNOTLAR
--INNER JOIN TBLDERSLER
--ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
--WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR')

--Ödev: AYÞE ÇINAR'ýn Algoritma dersinde almýþ olduðu 1. sýnav notunun sýnýf ortalamasýnýn üstünde mi yoksa altýnda mý olduðunu bulan sorgu
SELECT OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,ORTALAMA, 'ÜSTÜNDE' AS 'SONUÇ' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR') AND
DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='ALGORÝTMA') AND
SINAV1 >= (SELECT AVG(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='ALGORÝTMA'))
UNION
SELECT OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD',DERSAD,SINAV1,ORTALAMA, 'ALTINDA' AS 'SONUÇ' FROM TBLNOTLAR
INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
WHERE OGRENCI = (SELECT OGRID FROM TBLOGRENCILER WHERE OGRAD='AYÞE' AND OGRSOYAD='ÇINAR') AND
DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='ALGORÝTMA') AND
SINAV1 < (SELECT AVG(SINAV1) FROM TBLNOTLAR WHERE DERS = (SELECT DERSID FROM TBLDERSLER WHERE DERSAD='ALGORÝTMA'))