--ARÝTMETÝK ÝÞLEMLER
--SELECT 20+4 AS 'TOPLAM', 20-4 AS 'FARK', 20*4 AS 'ÇARPIM', 20/4 AS 'BÖLÜM'

--SINAV2 notu 45'in altýnda olan Ders 1'e ait olan öðrencilere 10 puan ekleyen sorgu
--UPDATE TBLNOTLAR SET SINAV2=SINAV2+10 FROM TBLNOTLAR WHERE DERS=1
--UPDATE TBLNOTLAR SET SINAV2=100 WHERE SINAV2>100
--SELECT * FROM TBLNOTLAR WHERE DERS=1

--UPDATE TBLNOTLAR SET ORTALAMA=(SINAV1+SINAV2+SINAV3)/3 WHERE DERS=1

--Sýnýfýn genel ortalamasýný hesaplayan sorgu
--SELECT AVG(ORTALAMA) FROM TBLNOTLAR WHERE DERS=1

--Sýnýf ortalamasýnýn altýnda olan öðrencilerin "Durum2" sütunlarýnýn yanýna "Altýnda", aksi durumda üstünde yazdýran sorguyu hazýrlayýn...
--SELECT NOTID, OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD', DERSAD, SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM, 'ÜSTÜNDE' AS 'DURUM2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
--INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
--WHERE ORTALAMA >= (SELECT AVG(ORTALAMA) FROM TBLNOTLAR)
--UNION
--SELECT NOTID, OGRAD + ' ' + OGRSOYAD AS 'AD SOYAD', DERSAD, SINAV1,SINAV2,SINAV3,ORTALAMA,DURUM, 'ALTINDA' AS 'DURUM2' FROM TBLNOTLAR
--INNER JOIN TBLOGRENCILER ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI
--INNER JOIN TBLDERSLER ON TBLDERSLER.DERSID = TBLNOTLAR.DERS
--WHERE ORTALAMA < (SELECT AVG(ORTALAMA) FROM TBLNOTLAR)