--Öðrenciler ile TBLNOTLAR tablosunda hem TBLOGRENCILER hem de TBLNOTLAR tablosunda olan bütün kayýtlarý getiren sorgu
SELECT * FROM TBLNOTLAR
FULL JOIN TBLOGRENCILER
ON TBLOGRENCILER.OGRID = TBLNOTLAR.OGRENCI

--TBLKULUPLER ile TBLDERSLER tablolarýný birleþtiren sorgu
SELECT * FROM TBLKULUPLER UNION SELECT * FROM TBLDERSLER