--VIEW (GÖRÜNÜM)

--View Oluþturma
--CREATE VIEW TEST1
--AS
--SELECT * FROM TBLKATEGORI

--View Çalýþtýrma
--SELECT * FROM TEST1

--View Güncelleme
--ALTER VIEW TEST1
--AS
--SELECT * FROM TBLKATEGORI WHERE KATEGORIID<4

--SELECT * FROM TEST1