--ALFABETÝK FONKSÝONLAR
--SELECT UPPER('merhaba') AS 'SÜTUN'

--SELECT UPPER(OGRAD) AS 'ÖÐRENCÝ ADI', UPPER(OGRSOYAD) AS 'SOYAD',
--LOWER(OGRSEHIR) AS 'ÞEHÝR' FROM TBLOGRENCILER

--TBLOGRENCILER tablosunda yer alan þehri Adana olan ve Biliþim kulübünde bulunan öðrencilerin adýný büyük, soyadýný küçük harfle getiren sorgu
SELECT UPPER(OGRAD) AS 'AD', LOWER(OGRSOYAD) AS 'SOYAD',KULUPAD FROM TBLOGRENCILER
INNER JOIN TBLKULUPLER ON TBLKULUPLER.KULUPID = TBLOGRENCILER.OGRKULUP
WHERE OGRSEHIR='Adana' AND KULUPAD='Biliþim'