--TBLOGRENCILER tablosuna yeni bir veri ekleme
--INSERT INTO TBLOGRENCILER (OGRAD,OGRSOYAD,OGRSEHIR) VALUES ('Sercan','Kurban','Ýstanbul')
--SELECT * FROM TBLOGRENCILER

--TBLNOTLAR tablosuna yeni bir veri ekleme
--INSERT INTO TBLNOTLAR (OGRENCI,DERS,SINAV1,SINAV3) VALUES (6,2,88,67)
--SELECT * FROM TBLNOTLAR