--T-SQL CASE ile KRITIK SEVIYE BULMAK

CREATE PROCEDURE TEST4
AS
SELECT URUNAD, URUNMARKA, URUNSTOK, URUNSTOK = 
CASE
WHEN URUNSTOK >= 1 AND URUNSTOK <= 5 THEN 'KRÝTÝK SEVÝYE'
WHEN URUNSTOK >= 6 AND URUNSTOK <= 10 THEN 'TAKVÝYE YAPILMALI'
WHEN URUNSTOK > 10 THEN 'ÜRÜN STOK SAYISI YETERLÝ'
END
FROM TBLURUNLER