--T-SQL CASE KULLANIMI

--SELECT URUNAD, URUNMARKA, URUNDURUM = CASE URUNDURUM
--WHEN '1' THEN 'ÜRÜN VAR'
--WHEN '0' THEN 'ÜRÜN YOK'
--END
--FROM TBLURUNLER

--SELECT URUNAD, URUNMARKA, KATEGORI = CASE KATEGORI
--WHEN '1' THEN 'LAPTOP'
--WHEN '2' THEN 'BEYAZ EÞYA'
--WHEN '3' THEN 'KÜÇÜK EV ALETÝ'
--END
--FROM TBLURUNLER